name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '0d9d4684352ba8de70bdf251c6fc9a3c464fa12b'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libncurses-dev
    
    - name: Set up compiler (GCC)
      if: matrix.compiler == 'gcc'
      run: |
        echo "CC=gcc" >> $GITHUB_ENV
        echo "CXX=g++" >> $GITHUB_ENV
    
    - name: Set up compiler (Clang)
      if: matrix.compiler == 'clang'
      run: |
        echo "CC=clang" >> $GITHUB_ENV
        echo "CXX=clang++" >> $GITHUB_ENV
    
    - name: Configure CMake
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G Ninja
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Run tests
      run: ctest --test-dir build --output-on-failure --build-config Release
    
    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.compiler }}
        path: build/Testing/Temporary/
